version: 2
registries:
  npm-npmjs:
    type: npm-registry
    url: https://registry.npmjs.org
    token: ${{ secrets.NPM_TOKEN_READ_ONLY_DEPENDABOT }}
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "07:00"
      timezone: "America/New_York"
    labels:
      - "actions"
      - "dependabot"
    assignees:
      - "jeffsays"
    reviewers:
      - "jeffsays"
    groups:
      actions-deps:
        patterns:
          - "*"
  - package-ecosystem: "npm"
    directory: "/"
    registries:
      - npm-npmjs
    schedule:
      interval: "daily"
      time: "07:30"
      timezone: "America/New_York"
    labels:
      - "dependencies"
      - "dependabot"
    assignees:
      - "jeffsays"
    reviewers:
      - "jeffsays"
    groups:
      prod-deps:
        dependency-type: "production"
      dev-deps:
        dependency-type: "development"
    allow:
      # Provide version updates for cumulusds packages
      - dependency-name: "@cumulusds/*"
        dependency-type: "all"
      # Provide security updates, but not version updates, for open-source packages
      - dependency-name: "*"
        dependency-type: "all"
    # Issue security updates, but not regular updates, for public packages
    ignore:
      - dependency-name: "*"
        update-types:
          - version-update:semver-major
          - version-update:semver-minor
          - version-update:semver-patch
