approvedGitRepositories:
  - "**"

enableColors: true

enableScripts: true

enableTelemetry: false

enableTimers: true

npmMinimalAgeGate: 3d

npmPreapprovedPackages:
  - "@cumulusds/*"

yarnPath: .yarn/releases/yarn-4.15.0.cjs
