name: 🚫 Blocker
description: File a production blocker.
title: "🚫 Blocker: "
labels: ["blocker"]
projects: ["CumulusDS/20"]
body:
  - type: markdown
    attributes:
      value: |
        # Context
  - type: textarea
    id: context
    attributes:
      label: What is the context of this blocker?
      description: |
        Links? References? Anything that will give us more context about the issue you are encountering!        
        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
      placeholder: What is blocked and why?
