name: 🚫 Blocker
description: File a production deployment blocker.
title: "🚫 Blocker: "
type: ""
labels: ["blocker"]
projects: ["CumulusDS/20"]
body:
  - type: markdown
    attributes:
      value: |
        # Context
  - type: textarea
    id: context
    attributes:
      label: What is the context of this blocker?
      description: |
        Links? References?
        Anything that will give us more context about why we cannot deploy this service!
        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
      placeholder: What is blocked and why?
    validations:
      required: true
  - type: textarea
    id: resolution
    attributes:
      label: What needs to be done in order to unblock this?
      description: |
        How can it be unblocked?
      placeholder: How can it be unblocked?
    validations:
      required: true
