name: 🐛 Bug
description: File a bug report.
title: "🐛 Bug: "
type: "bug"
labels: ["bug"]
projects: ["CumulusDS/20"]
body:
  - type: markdown
    attributes:
      value: |
        # Reproduction
  - type: textarea
    attributes:
      label: Steps To Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. In this environment...
        2. With this config...
        3. Run '...'
        4. See error...
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        # Expected Behavior
  - type: textarea
    id: expected-behavior
    attributes:
      label: What was the expected behavior?
      description: A concise description of what you expected to happen.
      placeholder: Tell us what you expected to see!
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        # Observed Behavior
  - type: textarea
    id: observed-behavior
    attributes:
      label: What happened?
      description: A concise description of what you're experiencing.
      placeholder: Tell us what you saw!
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        # Context
  - type: textarea
    id: context
    attributes:
      label: What is the context of this bug?
      description: |
        Links? References? Anything that will give us more context about the bug you are encountering!
        Example entity?  (connection, test pack, etc.)
        What site are you using?
        What username?
        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
      placeholder: Is there any additional context to help us understand what you were doing?
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        # Platform(s)
  - type: dropdown
    id: browsers
    attributes:
      label: What browser(s) are you seeing the problem on?
      multiple: true
      options:
        - Chrome
        - Edge
        - Firefox
        - Safari
        - Other
    validations:
      required: false
  - type: dropdown
    id: frontends
    attributes:
      label: What front ends are you using?
      multiple: true
      options:
        - Control Center
        - Workflow Builder
        - CMA
    validations:
      required: false
  - type: dropdown
    id: platforms
    attributes:
      label: What platform are you using?
      multiple: true
      options:
        - Android
        - iOS
    validations:
      required: false

  - type: textarea
    id: logs
    attributes:
      label: Relevant logs output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
