name: 🐛 Vulnerability
description: Open a vulnerability issue.
title: "⚠️ Vulnerability: "
type: "task"
labels: ["build", "dependencies", "needs triage", "platform", "security", "tech debt"]
projects: ["CumulusDS/20"]
body:
  - type: dropdown
    id: severity
    attributes:
      label: What Severity is the vulnerability
      multiple: true
      options:
        - LOW
        - MODERATE
        - HIGH
        - CRITICAL
    validations:
      required: true
  - type: markdown
    id: header-vulerability-information
    attributes:
      value: |
        # Vulnerability Information
  - type: textarea
    id: affected-version
    attributes:
      label: |
        ## Affected & resolved version(s)
      description: What is the range of affected version(s), what version(s) are patched?
      value: |
        | Affected Versions(s) | Resolved Version(s) |
        | -------------------- | ------------------- |
        | >= x.y.z, < x.y.a    | x.y.a               |
    validations:
      required: true
  - type: textarea
    id: cve-ghsa-id
    attributes:
      label: |
        ## CVE/GHSA IDs
      description: What is the CVE ID?  If there is not one, please enter the GHSA ID.
      placeholder: e.g. CVE-2024-12345
    validations:
      required: true
  - type: textarea
    id: current-version
    attributes:
      label: |
        ## Currently installed version(s)
      description: What version(s) are installed?  What is dependent on them?
      placeholder: Run `yarn why <package>` and/or `yarn why <package> -R` and copy/paste the output
    validations:
      required: false
  - type: markdown
    id: header-context
    attributes:
      value: |
        # Context/Additional Information
  - type: textarea
    id: context
    attributes:
      label: |
        ## Context
      placeholder: Is there any additional information or context you wish to provide?
    validations:
      required: false
