name: ðŸ› Vulnerability
description: Open a vulnerability issue.
title: "âš ï¸ Vulnerability: "
type: "task"
labels: ["build", "dependencies", "needs triage", "platform", "security", "tech debt"]
projects: ["CumulusDS/20"]
body:
  - type: dropdown
    id: severity
    attributes:
      label: What Severity is the vulnerability
      multiple: true
      options:
        - LOW
        - MODERATE
        - HIGH
        - CRITICAL
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        # Vulnerability Information
  - type: textarea
    attributes:
      label: Affected & resolved version(s)
      description: What is the range of affected version(s), what version(s) are patched?
      placeholder: |
        | Affected Versions(s) | Resolved Version(s) |
        |-|-|
        | >= x.y.z, < x.y.a    | x.y.a               |
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        ## CVE/GHSA ID
  - type: textarea
    id: expected-behavior
    attributes:
      label: CVE/GHSA IDs
      description: What is the CVE ID?  If there is not one, please enter the GHSA ID.
      placeholder: e.g. CVE-2024-12345
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        ## Currently installed version(s)
  - type: textarea
    id: observed-behavior
    attributes:
      label: Currently installed?
      description: What version(s) are installed?  What is dependent on them?
      placeholder: Run `yarn why <package>` and/or `yarn why <package> -R` and copy/paste the output
    validations:
      required: false
  - type: markdown
    attributes:
      value: |
        # Additional Information/Context
  - type: textarea
    id: context
    attributes:
      label: Context
      placeholder: Is there any additional information or context you wish to provide?
    validations:
      required: false
