name: "Label stale issues and PRs"
on: workflow_call
jobs:
  stale:
    name: Label Stale Issues/PRs
    runs-on: ubuntu-latest
    steps:
      - name: Stale labeler
        uses: actions/stale@v10
        with:
          exempt-all-milestones: true
          exempt-issue-labels: blocker,bug,keep alive
          exempt-pr-labels: blocker,bug,keep alive
          days-before-close: -1 # never close automatically - https://github.com/actions/stale?tab=readme-ov-file#days-before-close
          days-before-issue-stale: 90
          stale-issue-label: stale
          stale-issue-message: "This issue is stale because it has been open 90 days with no activity. Remove stale label or comment or this will be closed in 7 days."
          days-before-pr-stale: 30
          stale-pr-label: stale
          stale-pr-message: "This PR is stale because it has been open 30 days with no activity. Remove stale label or comment or this will be closed in 7 days."
